parameters:
#    gmi_user.example.class: GMI\UserBundle\Example

services:
#    gmi_user.example:
#        class: %gmi_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
